"""Feed writer for research scanner — prepends findings to docs/RESEARCH_FEED.md."""

import os
import re
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
FEED_PATH = ROOT / "docs" / "RESEARCH_FEED.md"

_BANNER = """\
# Research Feed

Auto-generated by scripts/research_scan.py. Newest runs at the top.
See docs/RESEARCH_SCANNER.md for the spec.

---
"""

_FINDINGS_RE = re.compile(r"^- \*\*(STRATEGY|EVIDENCE|RISK)\*\*", re.MULTILINE)


def _count_findings(claude_output: str) -> int:
    return len(_FINDINGS_RE.findall(claude_output))


def write_findings(
    claude_output: str,
    mode: str,
    run_at: datetime,
    feed_path: Path = FEED_PATH,
) -> int:
    count = _count_findings(claude_output)
    date_str = run_at.strftime("%Y-%m-%d %H:%M UTC")
    new_section = (
        f"## Run {date_str} (mode: {mode}) — {count} findings\n\n"
        f"{claude_output}\n\n"
        f"---\n"
    )

    if not feed_path.exists():
        body = _BANNER + "\n" + new_section
    else:
        existing = feed_path.read_text(encoding="utf-8")
        # Splice after the banner separator (first "---\n" line)
        sep = "---\n"
        idx = existing.find(sep)
        if idx == -1:
            # Malformed file — prepend banner + section
            body = _BANNER + "\n" + new_section + existing
        else:
            after_sep = idx + len(sep)
            body = existing[:after_sep] + "\n" + new_section + existing[after_sep:]

    tmp = feed_path.with_suffix(".tmp")
    tmp.write_text(body, encoding="utf-8")
    os.replace(tmp, feed_path)

    return count
