"""Odds API team names → football-data.co.uk names (covers all scanner leagues)."""

API_TO_FD = {
    # EPL
    "Manchester City":        "Man City",
    "Manchester United":      "Man United",
    "Tottenham Hotspur":      "Tottenham",
    "Newcastle United":       "Newcastle",
    "West Ham United":        "West Ham",
    "Brighton & Hove Albion": "Brighton",
    "Wolverhampton Wanderers":"Wolves",
    "Nottingham Forest":      "Nott'm Forest",
    "Sheffield United":       "Sheffield United",
    "Leicester City":         "Leicester",
    "Luton Town":             "Luton",
    # Bundesliga
    "Borussia Dortmund":      "Dortmund",
    "Bayer Leverkusen":       "Leverkusen",
    "Eintracht Frankfurt":    "Ein Frankfurt",
    "VfL Wolfsburg":          "Wolfsburg",
    "1. FC Union Berlin":     "Union Berlin",
    "SC Freiburg":            "Freiburg",
    "1. FSV Mainz 05":        "Mainz",
    "FC Augsburg":            "Augsburg",
    "VfB Stuttgart":          "Stuttgart",
    "TSG Hoffenheim":         "Hoffenheim",
    "SV Werder Bremen":       "Werder Bremen",
    "1. FC Heidenheim 1846":  "Heidenheim",
    "1. FC Heidenheim":       "Heidenheim",
    "VfL Bochum":             "Bochum",
    "FC St. Pauli":           "St Pauli",
    "Borussia Mönchengladbach": "M'gladbach",
    "Borussia Monchengladbach": "M'gladbach",
    # Bundesliga 2
    "Hamburger SV":           "Hamburg",
    "1. FC Kaiserslautern":   "Kaiserslautern",
    "FC Köln":                "FC Koln",
    "Fortuna Düsseldorf":     "Fortuna Dusseldorf",
    "Hertha BSC":             "Hertha",
    "Hannover 96":            "Hannover",
    "1. FC Nürnberg":         "Nurnberg",
    "Karlsruher SC":          "Karlsruhe",
    "SV Darmstadt 98":        "Darmstadt",
    "SpVgg Greuther Fürth":   "Greuther Furth",
    "SV Elversberg":          "Elversberg",
    "1. FC Magdeburg":        "Magdeburg",
    "SC Paderborn 07":        "Paderborn",
    "SSV Ulm 1846":           "Ulm",
    "Eintracht Braunschweig": "Braunschweig",
    "SSV Jahn Regensburg":    "Regensburg",
    # Serie A
    "AC Milan":               "Milan",
    "Inter Milan":            "Inter",
    "AS Roma":                "Roma",
    "SS Lazio":               "Lazio",
    "ACF Fiorentina":         "Fiorentina",
    "Hellas Verona":          "Verona",
    "US Monza":               "Monza",
    # Ligue 1
    "Paris Saint-Germain":    "Paris SG",
    "Paris Saint Germain":    "Paris SG",
    "Olympique de Marseille": "Marseille",
    "Olympique Lyonnais":     "Lyon",
    "AS Monaco":              "Monaco",
    "LOSC Lille":             "Lille",
    "Stade Rennais":          "Rennes",
    "OGC Nice":               "Nice",
    "RC Strasbourg":          "Strasbourg",
    "RC Lens":                "Lens",
    "FC Nantes":              "Nantes",
    "Toulouse FC":            "Toulouse",
    "FC Lorient":             "Lorient",
    "Stade de Reims":         "Reims",
    "Clermont Foot":          "Clermont",
    "Saint-Etienne":          "St Etienne",
    # Championship
    "Sheffield Wednesday":    "Sheffield Weds",
    "West Bromwich Albion":   "West Brom",
    "Oxford United":          "Oxford",
    "Preston North End":      "Preston",
    "Plymouth Argyle":        "Plymouth",
    "Blackburn Rovers":       "Blackburn",
    "Norwich City":           "Norwich",
    "Cardiff City":           "Cardiff",
    "Stoke City":             "Stoke",
    "Queens Park Rangers":    "QPR",
    "Hull City":              "Hull",
    "Derby County":           "Derby",
    "Swansea City":           "Swansea",
    "Coventry City":          "Coventry",
    "Leeds United":           "Leeds",
    "Birmingham City":        "Birmingham",
}
